# Generated by Django 6.1.1 on 2026-10-04 08:54

import apps.users.services.path_avatar
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.services.path_avatar.user_avatar_upload_to,
                verbose_name='Аватар',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='Группы, к которым принадлежит пользователь. Пользователь получит все права, предоставленные каждой из его групп.',
                related_name='user_set',
                related_query_name='user',
                to='auth.group',
                verbose_name='Группы',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(
                default=False,
                help_text='Обозначает, что пользователь имеет все права без их явного назначения.',
                verbose_name='Суперпользователь',
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(
                blank=True,
                help_text='Конкретные права этого пользователя.',
                related_name='user_set',
                related_query_name='user',
                to='auth.permission',
                verbose_name='Права пользователя',
            ),
        ),
    ]
